services:
  mympsu-api:
    build: .
    container_name: mympsu-api
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
      - modules.flags.env
    environment:
      DATABASE_URL: "postgresql://mympsu:${DATABASE_PASSWORD}@mympsu-db:5432/mympsu"
      PYTHONPATH: /app
    depends_on:
      - mympsu-db

  mympsu-db:
    image: postgres:16
    container_name: mympsu-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: mympsu
      POSTGRES_USER: mympsu
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - mympsu_postgres_data:/var/lib/postgresql/data

volumes:
  mympsu_postgres_data:
